dividohq/finance-plugin-magento2

README.md
etc/adminhtml/system.xml

Rename Cart threshold label to Minimum cart amount

Rename cart threshold to minimum cart amount

---

Helper/Data.php

Ignores sending child products in bundles to the credit request call so that the price is as expected

Added line to ignore basket products with a parent ID on credit request

---

Helper/Data.php
Observer/InvoicedObserver.php
etc/adminhtml/system.xml
etc/events.xml

Custom Functionality -  allows to watch for a divido order an automatically update invoiced status

pull in invoiced observer funciton

---

Helper/Data.php
Model/CreditRequest.php
Observer/SendNoEmail.php
Setup/UpgradeSchema.php
etc/events.xml
etc/module.xml

added new column referred in divido_lookup table and setting it 1 when application is referred
Placing order in pending state for referred application
Sending emails only when application is signed
customredirecturl fix as we will be adding store frontend url

Refer workflow changes

---

Model/CreditRequest.php

Logging as debug instead of warning as its getting logged in error logging app

Log changes

---

Model/CreditRequest.php

Fix for single quote ID multiple orders, fetching latest order with method code as divido_financing

Custom checkout option

---

CHANGELOG.md
Model/CreditRequest.php
composer.json
etc/module.xml

Update from 2.0.1 to 2.0.2 with fix for intl and also fix for configurable products

version bump

---

view/frontend/templates/product/view/widget.phtml

Swap out the dollar dollar bill - to play nice with others

update to not rely on shortcde $

---

Helper/Data.php
Model/Ui/ConfigProvider.php
etc/adminhtml/system.xml
view/frontend/web/divido-standard.css
view/frontend/web/template/payment/form.html

remove and place in config
add some width
add some width
add some width
remove dump

squash commits

---

Model/Adminhtml/Source/AllowedCountries.php
etc/adminhtml/system.xml
etc/config.xml

force spcific countries

---

Helper/Data.php

strip white from phone

---

view/adminhtml/templates/order/view/custom.phtml

We missed this update when we moved over to pence

Amount save is in pence but view is not

---

Model/CreditRequest.php

`$this->logger->debug()` does not log information unless the application is in development or `dev/debug/debug_logging` is enabled.
So decided to change to the logging to `info()` method so that the information is logged for the debugging  issue `00061010`

Addes fix to log info in production

---

Helper/Data.php
Model/CreditRequest.php

Getting a lot of `Divido: Bad request, mismatch in hash. Req:` during the `update` webhook process so wanted to add some additional logs to investigate.

Adds extra logs to debug mismatch hash issue

---

Helper/Data.php

Discount is being rounded to nearest pound
Jira ticket: https://divido.atlassian.net/browse/CRE-131

fix: round discount to pence

---

Model/CreditRequest.php

Jira ticket: https://divido.atlassian.net/browse/CRE-162

fix: remove referred status creating a new order

---

CHANGELOG.md
Helper/Data.php
composer.json
etc/module.xml

fix: update version

---

.github/pull_request_template.md

chore: PR template

---

CHANGELOG.md
Helper/Data.php
Model/Payment.php
composer.json

feat(enable-currency): [LM2-1248] Enable Danish Kronor currency

---

CHANGELOG.md
Helper/Data.php
composer.json

chore: bumps version

---

Helper/Data.php
composer.json
view/frontend/web/js/view/payment/method-renderer/divido-dividofinancing.js

Temporarily linearly adds the ING logo for ING tenants at checkout, whilst we wait for lender branding to carry out this task dynamically.

chore: temp ing icon

---

Api/CreditRequestInterface.php
Exceptions/LookupNotFoundException.php
Exceptions/OrderNotFoundException.php
Exceptions/UnusedWebhookException.php
Model/CreditRequest.php
Schemas/webhook.json
Test/Unit/Model/CreditRequestTest.php
Traits/ValidationTrait.php

This PR is a pretty comprehensive rewrite of the CreditRequest class, which handles Webhooks. Primarily it looks to break the functionality of the class into various methods so that a) it can be customised a little more easily, b) it can be tested a little more easily, c) it's not nearly so impossible to follow/understand.
There are a couple of changes to the functionality:
- Introduces a CREATION_STATUSES const array which triggers the construction of the Order when we receive the appropriate status (in this instance; READY or REFERRED, as outlined [here](https://divido.atlassian.net/browse/LM2-2297?atlOrigin=eyJpIjoiZTE2N2Q4Njk5ODcyNGZhNTk4Mzc4YmJhZTcyM2IwYjQiLCJwIjoiaiJ9))
- Triggers a request to update the merchant reference of an application with the Order ID when a webhook is …

feat: LM2-2297 referrals journey

---

Helper/Data.php
Model/CreditRequest.php
Test/Unit/Model/CreditRequestTest.php
composer.json

Quick PR to 
- replace a reference to a var that was removed in a previous PR
- Activate a quote before trying to turn it into an order (that's a thing that needs to be done, apparently)
- Update the test related to the last bullet point
- Bump the internal version
- Transition an accepted application to a `pending-payment` state

fix: some bugs
